version: "3.6"
services:
    redis:
        image: "redis:alpine"
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 30s
            timeout: 10s
            retries: 3
        ports:
            - 6379:6379
        networks:
            - my-net
networks:
    my-net:
        driver: bridge
